<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.ws.calendar.calendar.CalendarValidationUnitTest" tests="13" skipped="0" failures="0" errors="0" timestamp="2018-04-11T19:45:34" hostname="WS-NTB073" time="0.416">
  <properties/>
  <testcase name="validatesBaseCalendar" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.258"/>
  <testcase name="validatesCalendarParticipantTypeCustomer" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.006"/>
  <testcase name="validatesCalendarWithCalendarTypeInactive" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.005"/>
  <testcase name="validatesCalendarParticipantTypeLead" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.009"/>
  <testcase name="validatesCalendarParticipantTypeUser" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.011"/>
  <testcase name="validatesStartDateEqualsEndDate" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.004"/>
  <testcase name="validatesCalendarParticipantTypeLocation" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.003"/>
  <testcase name="validatesStartDateAfterEndDate" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.008"/>
  <testcase name="validatesCalendarWithoutCalendarType" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.004"/>
  <testcase name="validatesCalendarParticipantTypeExternal" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.01"/>
  <testcase name="validatesStartDateBeforeEndDate" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.01"/>
  <testcase name="validatesCalendarParticipantTypeContact" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.012"/>
  <testcase name="validatesCalendarWithCalendarTypeIdNull" classname="com.ws.calendar.calendar.CalendarValidationUnitTest" time="0.008"/>
  <system-out><![CDATA[[ERROR] 2018-04-11 16:45:34,485 - ?[1;31mcom.sollar.test.AbstractShiroTest: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.
?[m org.apache.shiro.UnavailableSecurityManagerException: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.
	at org.apache.shiro.SecurityUtils.getSecurityManager(SecurityUtils.java:123) ~[shiro-core-1.3.2.jar:1.3.2]
	at com.sollar.test.AbstractShiroTest.getSecurityManager(AbstractShiroTest.java:66) ~[commons-test-2.1.0-SNAPSHOT.jar:?]
	at com.sollar.test.AbstractShiroTest.tearDownShiro(AbstractShiroTest.java:73) [commons-test-2.1.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37) [mockito-core-1.10.19.jar:?]
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62) [mockito-core-1.10.19.jar:?]
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114) [gradle-testing-jvm-4.3.jar:4.3]
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57) [gradle-testing-jvm-4.3.jar:4.3]
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66) [gradle-testing-jvm-4.3.jar:4.3]
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51) [gradle-testing-base-4.3.jar:4.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-4.3.jar:4.3]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-4.3.jar:4.3]
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32) [gradle-messaging-4.3.jar:4.3]
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93) [gradle-messaging-4.3.jar:4.3]
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source) [?:?]
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108) [gradle-testing-base-4.3.jar:4.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-4.3.jar:4.3]
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-4.3.jar:4.3]
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146) [gradle-messaging-4.3.jar:4.3]
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128) [gradle-messaging-4.3.jar:4.3]
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404) [gradle-messaging-4.3.jar:4.3]
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) [gradle-base-services-4.3.jar:4.3]
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) [gradle-base-services-4.3.jar:4.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) [gradle-base-services-4.3.jar:4.3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
]]></system-out>
  <system-err><![CDATA[SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/leticia/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.8.2/36bc2a99b86be26ccdc51fe288458dc712d280c1/log4j-slf4j-impl-2.8.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/leticia/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.6/665e3de72f19ec66ac67d82612d7b8e6b3de3cd0/logback-classic-1.1.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
]]></system-err>
</testsuite>
